### ISSUE TITLE
Release and deploy 0.1.0

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/nodeagent2#1]
One thing that Maven complained about yesterday when I prepared the Orca release, was that the dependency orca.node-agent2:agentlib was only a SNAPSHOT (0.1-SNAPSHOT), and not a release.

This might be a good thing to start testing out our access/ability to push to Central Nexus.

I was thinking I might start looking at that today, doing it in small-ish steps again:

1. release version 0.1.0 of agentlib to the local nexus. (should be easy -- this ticket)
2. release version 0.1.1 of agentlib to central nexus. (might take some work to get right -- will create new ticket)

**Comment by ibaldin** [comment]
Go ahead and do a release on node agent and any plugins (na2-oscars-plugin and na2-exec-plugin). You are right agent lib can also be pushed to Nexus, it is a foundational library for building plugins.

-ilya

**Comment by hinchliff** [comment]
Version 0.1.0 is now available in the local repo: http://ci-dev.renci.org/nexus/content/repositories/geni-orca-libs/orca/node-agent2/agentlib/0.1.0/
