### ISSUE TITLE
Release and deploy 0.1.1 to Central

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/nodeagent2#2]
Following on from #1, will try to push 0.1.1. release artifacts to OSSRH in Sonatype Central Nexus repo.

**Comment by hinchliff** [comment]
gah. i completely forgot that i would need to change the groupId to be a subproject of org.renci, and the groupIds are a little messy in this project.  (The sub-modules probably should not have different groupIds)

I need to think about the best way to do this.

**Comment by hinchliff** [comment]
@ibaldin should the new groupId for this project be `org.renci.orca.node-agent2` or simply `org.renci.node-agent2` ?

**Comment by ibaldin** [comment]
Prolly the latter.
-ilya

**Comment by hinchliff** [comment]
[Success!](https://oss.sonatype.org/#nexus-search;quick~node-agent2)
