### ISSUE TITLE
OSCARS circuits are not immediately available

### ISSUE THREAD

**Issue by paul-ruth** [RENCI-NRIG/nodeagent2#3]
This issue occurs when a slice containing OSCARS circuits is shutdown and a new slice using the same VLAN is instantiated quickly.    In this case, the new VLAN will likely fail.  If you wait (~5 mins) the OSCARS will be available again.

Solutions to this issue are to either 1) ensure that a VLAN is available before ORCA is allowed to issue a ticket for it or 2) have the handler that instantiates a VLAN retry until the VLAN succeeds.  Since the OSCARS requests are serialized the having the handler wait may slow down many requests.

**Comment by ibaldin** [comment]
This is addressed in RENCI-NRIG/na2-oscars-plugin@fb473f03c30da548060f70d46092cb53f836499e

**Comment by ibaldin** [comment]
Will be deployed after review
